import {createClient} from '@supabase/supabase-js';
const db=createClient('https://fgomaujsdblpzxhnnqrg.supabase.co','sb_publishable_JOUqLZDnfGu_yCa6k6FVDQ_AYwpr72i');
const $=id=>document.getElementById(id);let items=[],selected=null,user=null,editing=false,busy=false,request=0;
const report=message=>{$('status').textContent=message};
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button[type=submit]').forEach(b=>b.disabled=true);report('');try{await fn()}catch(e){report(e.message||'Unable to save. Please try again.')}finally{busy=false;document.querySelectorAll('button[type=submit]').forEach(b=>b.disabled=false)}}
function check(r){if(r.error)throw r.error;return r.data}
function resetLog(){request++;$('conversation').hidden=true;$('welcome').hidden=false;$('body').value='';$('welcome').replaceChildren();const h=document.createElement('h2');h.textContent=selected?'Open the conversation.':'A place to keep the conversation.';const p=document.createElement('p');p.textContent=selected?'Click Log to view saved entries and add a new one.':'Add an item on the left, then open its log.';$('welcome').append(h,p)}
function select(id){selected=items.find(i=>i.id===id)||null;renderItems();resetLog()}
function renderItems(){const list=$('items');list.replaceChildren();$('count').textContent=items.length;$('title').textContent=selected?.name||'Select an item';for(const item of items){const row=document.createElement('div');row.setAttribute('role','option');row.setAttribute('aria-selected',String(selected?.id===item.id));row.id='item-'+item.id;row.textContent=item.name;row.onclick=()=>select(item.id);list.append(row)}if(selected)list.setAttribute('aria-activedescendant','item-'+selected.id);else list.removeAttribute('aria-activedescendant');for(const id of ['change','delete','log'])$(id).disabled=!selected}
$('items').onkeydown=e=>{if(!['ArrowDown','ArrowUp','Home','End'].includes(e.key)||!items.length)return;e.preventDefault();let i=items.findIndex(x=>x.id===selected?.id);i=e.key==='Home'?0:e.key==='End'?items.length-1:e.key==='ArrowDown'?Math.min(i+1,items.length-1):Math.max(i-1,0);select(items[i].id);$('item-'+items[i].id).scrollIntoView({block:'nearest'})};
async function loadItems(){items=check(await db.from('elliot_log_items_v1').select('id,name,created_at').order('created_at').order('id'));selected=items.find(i=>i.id===selected?.id)||null;renderItems()}
function dateLabel(value){const d=new Date(value);return `${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')} ${new Intl.DateTimeFormat('en-US',{weekday:'short'}).format(d)}`}
async function openLog(){if(!selected)return;const itemId=selected.id,seq=++request;const rows=[];for(let from=0;;from+=500){const batch=check(await db.from('elliot_log_records_v1').select('id,speaker,body,created_at').eq('item_id',itemId).order('created_at').order('id').range(from,from+499));rows.push(...batch);if(batch.length<500)break}if(seq!==request||selected?.id!==itemId)return;$('welcome').hidden=true;$('conversation').hidden=false;const records=$('records');records.replaceChildren();if(!rows.length){const p=document.createElement('p');p.textContent='No entries yet. Start the conversation below.';p.style.color='#60728a';records.append(p)}for(const row of rows){const article=document.createElement('article');article.className='record'+(row.speaker==='Other'?' other':'');const meta=document.createElement('div');meta.className='record-meta';const who=document.createElement('strong');who.textContent=row.speaker;const time=document.createElement('time');time.dateTime=row.created_at;time.textContent=dateLabel(row.created_at);time.title=new Date(row.created_at).toLocaleString();meta.append(who,time);const bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=row.body;article.append(meta,bubble);records.append(article)}records.scrollTop=records.scrollHeight}
$('log').onclick=()=>run(openLog);
function itemDialog(change){editing=change;$('dialog-title').textContent=change?'Change item':'Add item';$('item-name').value=change?selected.name:'';$('item-dialog').showModal();$('item-name').focus()}
$('add').onclick=()=>itemDialog(false);$('change').onclick=()=>selected&&itemDialog(true);$('cancel').onclick=()=>$('item-dialog').close();
$('item-form').onsubmit=e=>{e.preventDefault();run(async()=>{const name=$('item-name').value.trim();if(!name)throw Error('Enter an item name.');if(editing){if(!selected)throw Error('Select an item first.');check(await db.from('elliot_log_items_v1').update({name}).eq('id',selected.id).select().single())}else{const item=check(await db.from('elliot_log_items_v1').insert({name}).select().single());selected=item}await loadItems();$('item-dialog').close();resetLog()})};
$('delete').onclick=()=>{if(!selected||!confirm(`Delete “${selected.name}” and all its log entries?`))return;run(async()=>{check(await db.from('elliot_log_items_v1').delete().eq('id',selected.id).select().single());selected=null;await loadItems();resetLog()})};
$('compose').onsubmit=e=>{e.preventDefault();run(async()=>{if(!selected)throw Error('Select an item first.');const body=$('body').value.trim();if(!body)throw Error('Write an entry before saving.');const itemId=selected.id;check(await db.from('elliot_log_records_v1').insert({item_id:itemId,body,speaker:document.querySelector('input[name=speaker]:checked').value}).select().single());if(selected?.id===itemId){$('body').value='';await openLog();$('body').focus()}})};
$('login').onsubmit=e=>{e.preventDefault();run(async()=>{check(await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value}));$('password').value=''})};
$('signout').onclick=()=>run(async()=>check(await db.auth.signOut()));
async function setSession(session){const next=session?.user||null;if(user?.id===next?.id)return;user=next;selected=null;items=[];request++;$('auth').hidden=!!user;$('workspace').hidden=!user;$('signout').hidden=!user;renderItems();resetLog();if(user){try{await loadItems()}catch(e){report(e.message)}}}
db.auth.onAuthStateChange((event,session)=>{setTimeout(()=>setSession(session),0)});
db.auth.getSession().then(({data,error})=>error?report(error.message):setSession(data.session));
